{"name": "test_update_user_job_patch", "status": "broken", "statusDetails": {"message": "jsonschema.exceptions.ValidationError: 'zion resident' is not of type 'number'\n\nFailed validating 'type' in schema['properties']['job']:\n    {'type': 'number'}\n\nOn instance['job']:\n    'zion resident'", "trace": "def test_update_user_job_patch():\n        body = {\n            \"name\": \"morpheus\",\n            \"job\": \"zion resident\"\n        }\n        response = httpx.patch(BASE_URL + UPDATE_USER, json=body)\n        assert response.status_code == 200\n>       validate(response.json(), UPDATED_USER_SCHEME)\n\ntests\\update_user_data.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ninstance = {'job': 'zion resident', 'name': 'morpheus', 'updatedAt': '2024-09-30T12:32:42.711Z'}\nschema = {'properties': {'job': {'type': 'number'}, 'name': {'type': 'string'}}, 'required': ['job'], 'type': 'object'}\ncls = <class 'jsonschema.validators.Draft202012Validator'>, args = ()\nkwargs = {}\nvalidator = Draft202012Validator(schema={'properties': {'job': {'type': 'number'}, 'name': {'type': 'string'}}, 'required': ['job'], 'type': 'object'}, format_checker=None)\nerror = <ValidationError: \"'zion resident' is not of type 'number'\">\n\n    def validate(instance, schema, cls=None, *args, **kwargs):  # noqa: D417\n        \"\"\"\n        Validate an instance under the given schema.\n    \n            >>> validate([2, 3, 4], {\"maxItems\": 2})\n            Traceback (most recent call last):\n                ...\n            ValidationError: [2, 3, 4] is too long\n    \n        :func:`~jsonschema.validators.validate` will first verify that the\n        provided schema is itself valid, since not doing so can lead to less\n        obvious error messages and fail in less obvious or consistent ways.\n    \n        If you know you have a valid schema already, especially\n        if you intend to validate multiple instances with\n        the same schema, you likely would prefer using the\n        `jsonschema.protocols.Validator.validate` method directly on a\n        specific validator (e.g. ``Draft202012Validator.validate``).\n    \n    \n        Arguments:\n    \n            instance:\n    \n                The instance to validate\n    \n            schema:\n    \n                The schema to validate with\n    \n            cls (jsonschema.protocols.Validator):\n    \n                The class that will be used to validate the instance.\n    \n        If the ``cls`` argument is not provided, two things will happen\n        in accordance with the specification. First, if the schema has a\n        :kw:`$schema` keyword containing a known meta-schema [#]_ then the\n        proper validator will be used. The specification recommends that\n        all schemas contain :kw:`$schema` properties for this reason. If no\n        :kw:`$schema` property is found, the default validator class is the\n        latest released draft.\n    \n        Any other provided positional and keyword arguments will be passed\n        on when instantiating the ``cls``.\n    \n        Raises:\n    \n            `jsonschema.exceptions.ValidationError`:\n    \n                if the instance is invalid\n    \n            `jsonschema.exceptions.SchemaError`:\n    \n                if the schema itself is invalid\n    \n        .. rubric:: Footnotes\n        .. [#] known by a validator registered with\n            `jsonschema.validators.validates`\n    \n        \"\"\"\n        if cls is None:\n            cls = validator_for(schema)\n    \n        cls.check_schema(schema)\n        validator = cls(schema, *args, **kwargs)\n        error = exceptions.best_match(validator.iter_errors(instance))\n        if error is not None:\n>           raise error\nE           jsonschema.exceptions.ValidationError: 'zion resident' is not of type 'number'\nE           \nE           Failed validating 'type' in schema['properties']['job']:\nE               {'type': 'number'}\nE           \nE           On instance['job']:\nE               'zion resident'\n\n.venv\\Lib\\site-packages\\jsonschema\\validators.py:1332: ValidationError"}, "start": 1727699562271, "stop": 1727699562860, "uuid": "403edb0b-ec2d-40f5-bc2a-ab809cea00af", "historyId": "d81e398c538d95da68c45f2dfe33906a", "testCaseId": "d81e398c538d95da68c45f2dfe33906a", "fullName": "tests.update_user_data#test_update_user_job_patch", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "update_user_data"}, {"name": "host", "value": "Jane"}, {"name": "thread", "value": "15556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.update_user_data"}]}